version: '3'
services:
    api:
        build: backend/.  
        env_file:
            - .env        
        ports:
            - "8000:8000"
        volumes:
            - ./backend/:/code
        